### ISSUE TITLE
Everybody needs to check the presentation, for any errors. 

### ISSUE THREAD

**Issue by gabrielechiossi** [gabrielechiossi/CS-3560-PROJECT#2]
Let's make sure the pptx is ready before the presentation.
Let's check:
- spelling errors
- If all the informations that I put are right and make sense
The file to check is Milestone 2.pptx
Let's try to have this issue close by tomorrow at 4:15 PM.
Enjoy the work! Do not stress to much for Midterms.

**Comment by siraajwoods** [comment]
I corrected all spelling, grammatical, and language errors and added more context to certain slides where I saw fit to. I also added a slide at the end of the presentation.
