### ISSUE TITLE
Fix Wavesound position when having multiple recording

### ISSUE THREAD

**Issue by gabrielechiossi** [gabrielechiossi/CS-3560-PROJECT#4]
Guys we are getting close to having something working how we wanted it.
We have to fix the waveform and make it go with the music player and not staying all together. I will try to explain myself better with some pictures. 
This is what it should look like, a wave sound for each sound that goes with the player and buttons.
![immagine](https://user-images.githubusercontent.com/59843905/97500759-8d106880-1946-11eb-8476-6fffca0572d6.png)

This is what we have so far (2nd pic)
![immagine](https://user-images.githubusercontent.com/59843905/97500879-c34de800-1946-11eb-9cfe-764cdbd23d1e.png)

I believe to fix this we have to make wavesurfer a const with the other around line 66 to 96. I have been trying to do this but I haven't had much success. Let's try to fix it, I know we can do it. USE VERSION3.0 TO FIX THIS.

**Comment by Bmarschall** [comment]
changed **soundclips**.appendChild(clipContainer) to **waveform**.appendChild(clipContainer) and added called it further down the onstop function
