### ISSUE TITLE
Check PPT Milestone 3 for any error

### ISSUE THREAD

**Issue by gabrielechiossi** [gabrielechiossi/CS-3560-PROJECT#5]
You guys know the drill!!
Check the PPT Milestone3.pptx for any errors also add what you did for this milestone. 
When you guys are done with it push the right and corrected ppt in the master branch, DO NOT CREATE A NEW VERSION JUST SUB THIS VERSION WITH THE CORRECTED ONE.  After that, comment on this issue with what you did and close it.

**Comment by Bmarschall** [comment]
changed a few things
